local Lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Win = Lib.CreateLib("VERCO X NUGI X", "BloodTheme")
local T1 = Win:NewTab("Menu Aim")
local S1 = T1:NewSection("Fitur Aim")
S1:NewToggle("Aimlock","Target",function(s) _G.A=s end)
S1:NewToggle("Telekill","TK",function(s) _G.T=s end)
S1:NewToggle("Underkill","UK",function(s) _G.U=s end)
S1:NewToggle("Fly kill","FK",function(s) _G.F=s end)
S1:NewToggle("Esp Line","EL",function(s) _G.L=s end)
S1:NewToggle("Esp Box","EB",function(s) _G.B=s end)
local T2 = Win:NewTab("Menu Auto")
local S2 = T2:NewSection("Fitur Auto")
S2:NewToggle("AutoFarm","Farm",function(s) _G.Af=s end)
S2:NewButton("South bronx","TP",function() game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(100,20,100) end)
S2:NewButton("teleport apartemen jual","TP",function() game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-200,10,-150) end)
local T3 = Win:NewTab("Menu Mg")
local S3 = T3:NewSection("Fitur Mg")
S3:NewToggle("AutoMancing","Fish",function(s) _G.Am=s end)
S3:NewToggle("AutoKill Ikan","Kill",function(s) _G.Ai=s end)
S3:NewToggle("AutoJual","Sell",function(s) _G.Aj=s end)
local T4 = Win:NewTab("Menu Risk")
local S4 = T4:NewSection("Fitur Risk")
S4:NewToggle("AutoFinish","Finish",function(s) _G.An=s end)
S4:NewToggle("MultiJump","Jump",function(s) _G.Mj=s game:GetService("UserInputService").JumpRequest:Connect(function() if _G.Mj then game.Players.LocalPlayer.Character.Humanoid:ChangeState("Jumping") end end) end)
S4:NewToggle("TembusBeton","Noclip",function(s) _G.Nc=s game:GetService("RunService").Stepped:Connect(function() if _G.Nc then for _,v in pairs(game.Players.LocalPlayer.Character:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = false end end end end) end)
S4:NewButton("Teleport ke player","TP",function() print("TP") end)
S4:NewToggle("AutoJalanSendiri Fly ikuti Player","Follow",function(s) _G.Fl=s end)
local CG = game:GetService("CoreGui")
if CG:FindFirstChild("CT_Btn") then CG.CT_Btn:Destroy() end
local SG = Instance.new("ScreenGui",CG)
SG.Name = "CT_Btn"
local FR = Instance.new("Frame",SG)
FR.Size = UDim2.new(0,50,0,50)
FR.Position = UDim2.new(0.1,0,0.5,0)
FR.BackgroundColor3 = Color3.fromRGB(255,0,0)
FR.Active = true
FR.Draggable = true
local CR = Instance.new("UICorner",FR)
CR.CornerRadius = UDim.new(1,0)
local BT = Instance.new("TextButton",FR)
BT.Size = UDim2.new(1,0,1,0)
BT.BackgroundTransparency = 1
BT.Text = "CT"
BT.TextColor3 = Color3.fromRGB(0,0,0)
BT.TextSize = 20
BT.MouseButton1Click:Connect(function() local g = CG:FindFirstChild("VERCO X NUGI X") if g then g.Enabled = not g.Enabled end end)
